WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM hours
    WHERE HOUR < 23
)

SELECT h.HOUR, COALESCE(a.COUNT, 0) AS COUNT
FROM hours h
LEFT JOIN (
    SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY DATE_FORMAT(DATETIME, '%H')
) a ON h.HOUR = a.HOUR
ORDER BY h.HOUR;
