WITH USER21 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
PUR21 AS (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USER21)
    GROUP BY USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)
),
MONTHLY AS (
    SELECT YEAR, MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM PUR21
    GROUP BY YEAR, MONTH
)
SELECT 
    m.YEAR,
    m.MONTH,
    m.PURCHASED_USERS,
    ROUND(m.PURCHASED_USERS / CAST(u.TOTAL_USERS AS DECIMAL), 1) AS PURCHASED_RATIO
FROM 
    MONTHLY m
CROSS JOIN 
    (SELECT COUNT(*) AS TOTAL_USERS FROM USER21) u
ORDER BY 
    m.YEAR, m.MONTH;
