WITH A AS (
SELECT h.HISTORY_ID,
       h.CAR_ID,
       DATEDIFF(h.END_DATE, h.START_DATE)+1 DD,
       c.DAILY_FEE,
       CASE WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 90 THEN "90일 이상"
       WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 30 THEN "30일 이상"
       WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 7 THEN "7일 이상"
       ELSE DATEDIFF(h.END_DATE, h.START_DATE)+1
       END DIFF
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h 
LEFT JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = "트럭"
), B AS (
SELECT CAR_TYPE,
       DURATION_TYPE,
       DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE = "트럭")

SELECT DISTINCT a.HISTORY_ID,
       ROUND(IF(b.DURATION_TYPE IS NULL, a.DD * a.DAILY_FEE, a.DD * (100 - b.DISCOUNT_RATE) * 0.01 * a.DAILY_FEE)) FEE
FROM a 
LEFT JOIN b ON a.DIFF = b.DURATION_TYPE
ORDER BY DURATION_TYPE DESC, CAR_TYPE DESC
