SELECT c.CAR_ID, 
       c.CAR_TYPE,
       ROUND((c.DAILY_FEE * ((100 - p.DISCOUNT_RATE) * 0.01)) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c 
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
# 30일 이상 대여가능한 조건으로 조인
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
# END_DATE와 START_DATE 날짜 조건
AND (h.END_DATE IS NULL OR h.END_DATE < '2022-11-01' OR h.START_DATE > '2022-11-30')
GROUP BY c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE, p.DISCOUNT_RATE
# 요금 계산
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;


WITH AvailableCars AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID
    # 대여 날짜 조건
    AND R.END_DATE >= '2022-11-01'
    AND R.START_DATE <= '2022-11-30'
    # 자동차 종류 조건
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND R.CAR_ID IS NULL -- 대여 기록이 없는 경우
),
DiscountedCars AS (
    SELECT AC.CAR_ID, AC.CAR_TYPE, AC.DAILY_FEE,
    # 30일간 대여 가능하 자동자의 요
           CASE WHEN DP.DURATION_TYPE = '30일 이상' THEN AC.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)
           ELSE AC.DAILY_FEE * 30
           END AS FEE
    FROM AvailableCars AC
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON AC.CAR_TYPE = DP.CAR_TYPE
    AND DP.DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM DiscountedCars
# 요금 제한
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
