SELECT
    TEACHER_ID,
    COUNT(IF(SUBJECT_ID>0,1,NULL)) AS CNT
FROM
    (SELECT
        TEACHER_ID,
        SUBJECT_ID
    FROM
        TEACHER
    GROUP BY
        TEACHER_ID,
        SUBJECT_ID) AS GB
GROUP BY
    TEACHER_ID;
