# CTE를 이용해 리뷰 많이 쓴 순서대로 랭킹
WITH CTE AS (
SELECT MEMBER_ID,
       RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) as rk
FROM REST_REVIEW
GROUP BY MEMBER_ID
)
SELECT mp.MEMBER_NAME,
       rr.REVIEW_TEXT,
       DATE_FORMAT(rr.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM CTE
LEFT JOIN MEMBER_PROFILE mp on cte.MEMBER_ID = mp.MEMBER_ID
# 랭킹 1등의 모든 리뷰를 불러오기 위해 JOIN
LEFT JOIN REST_REVIEW rr on cte.MEMBER_ID = rr.MEMBER_ID
# 랭킹 1등만 불러오기
WHERE CTE.rk = 1
ORDER BY rr.REVIEW_DATE, rr.REVIEW_TEXT
