# CTE : 50만원이상 200만원 미만 조건
WITH PRICE AS (SELECT CAR_ID, CAR.CAR_TYPE,
     FLOOR(DAILY_FEE*((100-DISCOUNT_RATE)*0.01)*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLA
ON CAR.CAR_TYPE = PLA.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상'
AND (CAR.CAR_TYPE = '세단' OR CAR.CAR_TYPE ='SUV')
AND (FLOOR(DAILY_FEE*((100-DISCOUNT_RATE)*0.01)*30) BETWEEN 500000 AND 1999999)
)

# MAIN : 11월 대여가능 조건
SELECT CAR.CAR_ID,
       CAR.CAR_TYPE,
       FLOOR(PRI.FEE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN PRICE AS PRI
ON CAR.CAR_ID=PRI.CAR_ID
WHERE CAR.CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE END_DATE >= '2022-11-01')
