WITH FIRST AS (
    SELECT
        CUSTOMER_ID,
        MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
        CUSTOMER_PREF_DELIVERY_DATE
    FROM DELIVERY
    GROUP BY CUSTOMER_ID
    )

SELECT 
    ROUND(
        (COUNT(IF(FIRST_ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE, 1, NULL)) 
        / COUNT(*)) * 100, 2
    ) AS immediate_percentage
FROM 
    FIRST;
