SELECT S.USER_ID, IFNULL(ROUND(SUM(CASE WHEN C.ACTION = 'confirmed' THEN 1 ELSE 0 END)/COUNT(C.USER_ID), 2), 0) AS CONFIRMATION_RATE
FROM SIGNUPS AS S LEFT JOIN CONFIRMATIONS AS C ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID;
