SELECT b.TITLE, r.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'   -- 어느 테이블에서 조건을 거는 것인지 잘 확인할 것
ORDER BY CREATED_DATE ASC, b.TITLE ASC
