# -*- coding: utf-8 -*-
"""A_ChessPieces_PNY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Anyb8dw03D3fGKBR8llEDPjqrwHDXQGa

# 백준 30003번 문제

* 시도 1
"""

chess = [1,1,2,2,2,8]
need = []

now = list(map(int, input().split()))

for a,b in zip(chess, now):
  need.append(a-b)

print(need)

"""* 시도 2, 3"""

chess = [1,1,2,2,2,8]

now = list(map(int, input().split()))

for a,b in zip(chess, now):
  print(a-b, end=" ")  # end = ""  > 공백 안 줘서 틀림