WITH G AS (
    SELECT
        CASE WHEN GROUP_CONCAT(S.NAME) LIKE '%Python%' AND (SUM(S.CATEGORY = 'Front End') > 0) THEN 'A'
        WHEN GROUP_CONCAT(S.NAME) LIKE '%C#%' THEN 'B'
        WHEN SUM(S.CATEGORY = 'Front End') > 0 AND GROUP_CONCAT(S.NAME) NOT LIKE '%Python%' THEN 'C'
        END GRADE,
        ID,
        EMAIL
    FROM
        DEVELOPERS D JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
    GROUP BY
        D.ID, D.EMAIL
)
SELECT GRADE, ID, EMAIL
FROM G
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
